name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: CanarysPlayground/Reusable-workflow/.github/workflows/workflow-A.yml@master

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
